"""
Phase 12b, step 4.1: re-run the exact same CIR benchmark evaluation as phase
12 (identical harness, `cir_eval.py`, pointed directly at phase 12's
`cir_benchmark.json` -- see that module's docstring), on the newly retrained
`controllable_modes_fixed.pt` checkpoint, with phase 12's own numbers carried
forward alongside for a direct before/after comparison.

Phase 12's substitute/complement/blend Recall@K numbers are hardcoded below
exactly as reported in `week4/phase12_controllable_modes/results_table.md`
(generated by that phase's own `04_evaluate_cir_all_modes.py`) -- not
recomputed here, since phase 12's checkpoint and benchmark are untouched and
reusing the published numbers directly avoids any risk of silent drift.
"""
import json
import sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent))
from cir_eval import evaluate_recall, load_benchmark
from model import ControllableProjectionHead

BASE_DIR = Path(__file__).resolve().parent.parent
PHASE9_DIR = BASE_DIR.parent.parent / "week3" / "phase9_polyvore_compatibility"
PHASE12_DIR = BASE_DIR.parent / "phase12_controllable_modes"
EMBEDDINGS_NPZ = PHASE9_DIR / "embeddings" / "siglip_base.npz"
CHECKPOINT = BASE_DIR / "models" / "controllable_modes_fixed.pt"
RESULTS_MD = BASE_DIR / "results_table.md"

DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"
KS = (10, 30, 50)

# From week4/phase12_controllable_modes/results_table.md (phase 12's own run) --
# raw SigLIP / phase 9 Model A rows from that phase's data/baseline_recall.json.
PHASE12_NUMBERS = {
    "Raw SigLIP (alone)": {10: 0.0553, 30: 0.1067, 50: 0.1437},
    "Phase 9 Model A (Polyvore-trained, alone)": {10: 0.1317, 30: 0.2464, 50: 0.3216},
    "Substitute mode alone (alpha=1.0)": {10: 0.1329, 30: 0.2467, 50: 0.3215},
    "Complement mode alone (alpha=0.0)": {10: 0.1335, 30: 0.2507, 50: 0.3250},
    "Interpolated blend (alpha=0.5)": {10: 0.1366, 30: 0.2524, 50: 0.3289},
}
LITERATURE_ANCHOR = {10: 0.0958, 30: 0.1796, 50: 0.2198}


def load_raw_embeddings():
    data = np.load(EMBEDDINGS_NPZ, allow_pickle=True)
    item_ids = [str(a) for a in data["item_ids"]]
    embeddings = data["embeddings"]
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
    return item_ids, (embeddings / norms).astype(np.float32)


@torch.no_grad()
def project(model, embeddings, alpha, batch_size=4096):
    outs = []
    for start in range(0, len(embeddings), batch_size):
        x = torch.tensor(embeddings[start:start + batch_size], device=DEVICE)
        outs.append(model(x, alpha=alpha).cpu().numpy())
    return np.concatenate(outs, axis=0)


def fmt_row(label, recall, n=None):
    n_str = n if n is not None else "--"
    return f"| {label} | {recall[10]:.4f} | {recall[30]:.4f} | {recall[50]:.4f} | {n_str} |"


def delta_str(new, old):
    d = new - old
    sign = "+" if d >= 0 else ""
    return f"{sign}{d:.4f}"


def main():
    pools, queries = load_benchmark()
    item_ids, raw_emb = load_raw_embeddings()

    model = ControllableProjectionHead().to(DEVICE)
    model.load_state_dict(torch.load(CHECKPOINT, map_location=DEVICE))
    model.eval()

    configs = [
        ("Substitute mode alone (alpha=1.0)", 1.0),
        ("Complement mode alone (alpha=0.0)", 0.0),
        ("Interpolated blend (alpha=0.5)", 0.5),
    ]

    new_rows = {}
    for label, alpha in configs:
        emb = project(model, raw_emb, alpha)
        recall, n, n_skip = evaluate_recall(pools, queries, item_ids, emb, ks=KS)
        new_rows[label] = (recall, n, n_skip)
        print(f"{label}: {recall} (n={n}, {n_skip} skipped)")

    with open(BASE_DIR / "data" / "phase12b_recall.json", "w") as f:
        json.dump({label: {"recall": {str(k): v for k, v in r.items()}, "n_queries": n, "n_skipped": s}
                   for label, (r, n, s) in new_rows.items()}, f, indent=2)

    lines = [
        "# Phase 12b: CIR Benchmark Results, Before/After Comparison With Phase 12",
        "",
        f"Same benchmark as phase 12 (`week4/phase12_controllable_modes/data/cir_benchmark.json`, "
        f"unchanged): {sum(len(v) for v in pools.values())} pool slots across 11 categories, "
        f"{len(queries)} leave-one-out queries.",
        "",
        "## Recall@K -- phase 12 (batch-local pairwise substitute loss) vs phase 12b "
        "(fixed: direct global PCA-128 target + verified loss balancing)",
        "",
        "| Configuration | Recall@10 | Recall@30 | Recall@50 | N queries |",
        "|---|---|---|---|---|",
    ]
    lines.append(fmt_row("Raw SigLIP (alone) [reference]", PHASE12_NUMBERS["Raw SigLIP (alone)"], 29681))
    lines.append(fmt_row("Phase 9 Model A (alone) [reference]", PHASE12_NUMBERS["Phase 9 Model A (Polyvore-trained, alone)"], 29681))
    lines.append("| | | | | |")
    for label, alpha in configs:
        old = PHASE12_NUMBERS[label]
        lines.append(fmt_row(f"Phase 12: {label}", old, 29681))
        new_recall, n, n_skip = new_rows[label]
        lines.append(fmt_row(f"**Phase 12b: {label}**", new_recall, n))
        deltas = {k: delta_str(new_recall[k], old[k]) for k in KS}
        lines.append(f"| &nbsp;&nbsp;&nbsp;&nbsp;*delta (12b - 12)* | {deltas[10]} | {deltas[30]} | {deltas[50]} | |")
        lines.append("| | | | | |")
    lines.append(fmt_row("OutfitTransformer (literature anchor, not independently reproduced)", LITERATURE_ANCHOR))
    lines.append("")
    lines.append(
        "**Reading this table**: the headline question is not whether Recall@K went up, but "
        "whether **substitute mode's** Recall@K moved DOWN toward raw SigLIP's much lower range "
        "(0.055 @10) -- that would indicate it is finally behaving like genuine visual "
        "similarity rather than a weakly-offset copy of the compatibility-trained signal. See "
        "`control_effectiveness.md` for the direct behavioral checks (overlap, per-item cosine, "
        "and the two-axis diagnostic) that actually settle whether the fix worked -- Recall@K "
        "alone was already shown in phase 12 to look deceptively reasonable even when the two "
        "modes were barely distinguishable."
    )
    lines.append("")

    RESULTS_MD.write_text("\n".join(lines) + "\n")
    print(f"\nSaved {RESULTS_MD}")


if __name__ == "__main__":
    main()
